version: '3.8'

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rental_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      # Add database connection details
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rental_db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
